baseURL = "https://colelavallee.io"
languageCode = "en-us"
title = "colelavallee.io"
author = "Cole Lavallee"
theme = "monopriv"
paginate = 3
enableInlineShortcodes = true
enableEmoji = true
summaryLength = 20

[params]
about = "Cloud. Automation. Infosec."
github = "https://github.com/colealtdelete"
linkedin = "https://linkedin.com/in/colelavallee"
goodreads = "https://goodreads.com/colealtdelete"

[params.hero]
enabled = true
img = "img/cole_crop.png"
