baseURL = "https://www.colelavallee.io
languageCode = "en-us"
title = "colelavallee.io"
author = "Cole Lavallee"
theme = "monopriv"
paginate = 3
enableInlineShortcodes = true
enableEmoji = true
summaryLength = 20

[params]
about = "Cats. Computers. Coffee."
github = "https://github.com/colealtdelete"
linkedin = "https://linkedin.com/in/colelavallee"

[params.hero]
enabled = true
img = "img/cole_crop.png"